<a href="https://colab.research.google.com/github/amann1273/B5_PFDS_1273/blob/main/PFDS_lab_2_programs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#q1
def factorial(n):
    print(f"factorial({n}) called")
    if n == 0 or n == 1:
        print(f"Returning 1 (base case)")
        return 1
    else:
        result = n * factorial(n - 1)
        print(f"Returning {result} from factorial({n})")
        return result

num = int(input("Enter a number (0 to 10): "))
if num < 0 or num > 10:
    print("Please enter a number between 0 and 10")
else:
    print(f"\nStarting factorial of {num}\n")
    answer = factorial(num)
    print(f"\nFactorial of {num} is: {answer}")

Enter a number (0 to 10): 9

Starting factorial of 9

factorial(9) called
factorial(8) called
factorial(7) called
factorial(6) called
factorial(5) called
factorial(4) called
factorial(3) called
factorial(2) called
factorial(1) called
Returning 1 (base case)
Returning 2 from factorial(2)
Returning 6 from factorial(3)
Returning 24 from factorial(4)
Returning 120 from factorial(5)
Returning 720 from factorial(6)
Returning 5040 from factorial(7)
Returning 40320 from factorial(8)
Returning 362880 from factorial(9)

Factorial of 9 is: 362880


In [ ]:
#q2
import numpy as np

# Format: [ [Math, Physics, Chemistry], ... ]
marks = np.array([
    [85, 78, 92],
    [70, 65, 80],
    [90, 88, 84],
    [60, 75, 70],
    [95, 98, 99]
])

print("Student Marks (rows=students, cols=subjects):\n", marks)

student_avg = np.mean(marks, axis=1)
student_min = np.min(marks, axis=1)
student_max = np.max(marks, axis=1)

print("\nAverage marks per student:", student_avg)
print("Minimum marks per student:", student_min)
print("Maximum marks per student:", student_max)

print("\nMarks of 3rd student:", marks[2])

above_80 = student_avg > 80
print("\nStudents with average marks > 80:\n", marks[above_80])

reshaped = marks.T
print("\nSubject-wise Performance (rows=subjects):\n", reshaped)

Student Marks (rows=students, cols=subjects):
 [[85 78 92]
 [70 65 80]
 [90 88 84]
 [60 75 70]
 [95 98 99]]

Average marks per student: [85.         71.66666667 87.33333333 68.33333333 97.33333333]
Minimum marks per student: [78 65 84 60 95]
Maximum marks per student: [92 80 90 75 99]

Marks of 3rd student: [90 88 84]

Students with average marks > 80:
 [[85 78 92]
 [90 88 84]
 [95 98 99]]

Subject-wise Performance (rows=subjects):
 [[85 70 90 60 95]
 [78 65 88 75 98]
 [92 80 84 70 99]]
